# Generated by Django 2.0.5 on 2018-05-31 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя учащегося', max_length=100)),
                ('last_name', models.CharField(help_text='Фамилия учащегося', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.CharField(help_text='Класс', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата')),
                ('status', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=10)),
                ('people', models.ForeignKey(help_text='Фамилия и имя учащегося', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peoples', to='app.People')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='people',
            name='school_class',
            field=models.ForeignKey(help_text='Класс ученика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SchoolClass'),
        ),
    ]
