# Generated by Django 2.0.5 on 2018-05-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180531_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['people', '-date']},
        ),
    ]
