# Generated by Django 2.0.5 on 2018-05-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180531_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['people', 'date']},
        ),
    ]
