# Generated by Django 2.0.5 on 2018-05-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180531_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['school_class']},
        ),
    ]
