# Generated by Django 2.0.5 on 2018-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180602_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='people',
            field=models.ManyToManyField(blank='true', help_text='Фамилия и имя учащегося', related_name='peoples', to='app.People'),
        ),
    ]
