# Generated by Django 2.0.5 on 2018-06-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180603_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SchoolClass'),
        ),
    ]
