# Generated by Django 2.0.5 on 2018-06-03 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_state_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='school_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
