# Generated by Django 2.0.5 on 2018-06-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180603_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
