# Generated by Django 2.0.5 on 2018-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180605_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='school_class_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
