# Generated by Django 2.0.5 on 2018-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_state_school_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='author',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.DateField(help_text='- в формате гггг-мм-дд'),
        ),
        migrations.AlterField(
            model_name='state',
            name='people',
            field=models.ManyToManyField(blank='true', help_text='-выберите только тех, кто пришел!', related_name='peoples', to='app.People'),
        ),
    ]
