# Generated by Django 2.0.5 on 2018-07-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_state_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.DateField(help_text='- в формате дд.мм.гггг'),
        ),
    ]
