# Generated by Django 2.0.5 on 2018-07-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180729_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-date']},
        ),
    ]
