# Generated by Django 2.0.5 on 2018-08-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180730_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='stats',
            field=models.BigIntegerField(default=0),
        ),
    ]
