# Generated by Django 2.1.1 on 2018-09-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_schoolclass_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='stats',
        ),
    ]
